server:
  port: 51514
  allowedOrigins:
    - "http://localhost:3000"
db:
  host: postgres
  port: 5432
  user: postgres
  password: passwd
  database: postgres
  schema: media
  sslmode: disable
file:
  mediaRoot: /mnt/g
  thumbRoot: /mnt/g/thumbgen
  castRoot: /mnt/g/models
  maxStreamSize: 2097152
auth:
  secret: secret
  mediaSecret: msecret
  tokenDuration: 2592000
  mediaTokenDuration: 3600
log:
  path: var/log/verse.log

