server:
  port: 51514
  allowedOrigins:
    - "*"
db:
  host: localhost
  port: 54321
  user: postgres
  password: passwd
  database: postgres
  schema: media
  sslmode: disable
file:
  mediaRoot: /mnt/f
  thumbRoot: /soft/thumbgen/work/out
  maxStreamSize: 1048576
auth:
  secret: secret
  mediaSecret: msecret
log:
  path: ext/log/verse.log

