server:
  port: 51514
  allowedOrigins:
    - "http://localhost:5173"
db:
  host: localhost
  port: 54321
  user: postgres
  password: passwd
  database: postgres
  schema: media
  sslmode: disable
file:
  mediaRoot: /mnt/f
  thumbRoot: /soft/thumbgen/work/out
  castRoot: /mnt/f/models
  maxStreamSize: 2097152
auth:
  secret: secret
  mediaSecret: msecret
log:
  path: ext/log/verse.log

